Improve checkpresent

diff --git a/git-annex-remote-gdrive b/git-annex-remote-gdrive
--- a/git-annex-remote-gdrive
+++ b/git-annex-remote-gdrive
@@ -213,19 +213,16 @@ while read -r line; do
 		;;
 		CHECKPRESENT)
 			key="$2"
-			calclocation "$key"
-			if check_result=$(gdrive list -q "name = '$key' " --no-header --bytes --name-width 0 2>&1) &&
-			    echo $check_result|grep "$key" >&2; then
-				echo CHECKPRESENT-SUCCESS "$key"
+			if ! check_result=$(gdrive list -q "name = '$key' " --no-header --bytes --name-width 0 2>&1)
+			then
+				echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-gdrive failed to parse gdrive output"
 			else
-				echo CHECKPRESENT-FAILURE "$key"
-				# need to implement this:
-				# When the directory does not exist,
-				# the remote is not available.
-				# (A network remote would similarly
-				# fail with CHECKPRESENT-UNKNOWN
-				# if it couldn't be contacted).
-				#echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-gdrive failed to parse gdrive output"
+				if echo $check_result|grep "$key" &>/dev/null
+				then
+					echo CHECKPRESENT-SUCCESS "$key"
+				else
+					echo CHECKPRESENT-FAILURE "$key"
+				fi
 			fi
 		;;
 		REMOVE)
