Add support for multiple gdrive configs (aka google accounts)

diff --git a/git-annex-remote-gdrive b/git-annex-remote-gdrive
--- a/git-annex-remote-gdrive
+++ b/git-annex-remote-gdrive
@@ -47,6 +47,17 @@ validate_layout() {
 	esac		
 }
 
+validate_config_path() {
+	if [ -z "$CONFIG_PATH" ]; then
+		CONFIG=""
+	else
+		CONFIG=" -c ${CONFIG_PATH/#\~/$HOME}" # expand ~
+		if [ ! -f "${CONFIG_PATH/#\~/$HOME}/token_v2.json" ]; then
+			return 1
+		fi
+	fi
+}
+
 # Sets FID to the parent id to use to store a key.
 calcparent () {
 	case "$GDRIVE_LAYOUT" in
@@ -85,12 +96,12 @@ getfolderid () {
 	local folder_result
 	for dir in "${path[@]}"
 	do
-		if ! folder_result=$(gdrive list -m 1 -q "'$id' in parents and name = '$dir' and trashed = false" --no-header)
+		if ! folder_result=$(gdrive list $CONFIG -m 1 -q "'$id' in parents and name = '$dir' and trashed = false" --no-header)
 		then return 1
 		fi
 		new_id=$(echo $folder_result | awk '{print $1;}')
 		if [ -z "$new_id" ]; then
-			if ! folder_result=$(gdrive mkdir -p $id $dir)
+			if ! folder_result=$(gdrive mkdir $CONFIG -p $id $dir)
 			then return 2
 			fi
 			id=$(echo $folder_result | awk '{print $2;}')
@@ -139,6 +150,15 @@ while read -r line; do
 			# (Note that this is not run every time, only when
 			# git annex initremote or git annex enableremote is
 			# run.)
+			
+			getconfig config_path
+			CONFIG_PATH="$RET"
+			if ! validate_config_path; then
+				echo "INITREMOTE-FAILURE No config found. Please run 'gdrive about$CONFIG'"
+				exit 1
+			fi
+			setconfig config_path $CONFIG_PATH
+
 
 			getconfig prefix
 			REMOTE_PREFIX=$RET
@@ -150,10 +170,6 @@ while read -r line; do
 				exit 1
 			fi
 			setconfig prefix $REMOTE_PREFIX
-
-			getconfig config_path
-			CONFIG_PATH=$RET
-			setconfig config_path $CONFIG_PATH
 
 			getconfig traverse
 			TRAVERSE_MODE=$RET
@@ -196,6 +212,14 @@ while read -r line; do
 			# Use GETCONFIG to get configuration settings,
 			# and do anything needed to get ready for using the
 			# special remote here.
+			
+			getconfig config_path 
+			CONFIG_PATH="$RET"
+			if ! validate_config_path; then
+				echo "PREPARE-FAILURE No config found. Please run 'gdrive about$CONFIG'"
+				exit 1
+			fi
+
 
 			getconfig prefix
 			REMOTE_PREFIX="$RET"
@@ -210,10 +234,7 @@ while read -r line; do
 			if [[ $ROOT_ID != $RET ]]; then
 				PREPARE_FAILURE="ID of root folder changed. Was the repo moved? Please check remote and re-run git annex enableremote"
 			fi
-			
-			getconfig config_path 
-			CONFIG_PATH="$RET"
-			
+
 			getconfig traverse
 			TRAVERSE_MODE=$RET
 			
@@ -244,8 +265,8 @@ while read -r line; do
 						calcparent $key
 						query="name = '$key' and '$FID' in parents and trashed = false"
 
-						if (gdrive list -q "$query" --no-header --name-width 0 2>&1 | grep "$key" &>/dev/null) ||
-							runcmd gdrive upload -p $FID "$file"
+						if (gdrive list $CONFIG -q "$query" --no-header --name-width 0 2>&1 | grep "$key" &>/dev/null) ||
+							runcmd gdrive upload $CONFIG -p $FID "$file"
 						then
 							echo TRANSFER-SUCCESS STORE "$key"
 						else
@@ -266,10 +287,10 @@ while read -r line; do
 						calcparent $key
 						query="name = '$key' and '$FID' in parents and trashed = false"
 					fi
-					FID=$(gdrive list -q "$query" -m 1 --no-header | awk '{print $1}')
+					FID=$(gdrive list $CONFIG -q "$query" -m 1 --no-header | awk '{print $1}')
 					# http://stackoverflow.com/questions/31396985/why-is-mktemp-on-os-x-broken-with-a-command-that-worked-on-linux
 					if GA_RC_TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/gdrive-annex-tmp.XXXXXXXXX") &&
-					    runcmd gdrive download $FID --path $GA_RC_TEMP_DIR &&
+					    runcmd gdrive download $CONFIG $FID --path $GA_RC_TEMP_DIR &&
 					    mv $GA_RC_TEMP_DIR/$key $file &&
 					    rmdir $GA_RC_TEMP_DIR; then
 						echo TRANSFER-SUCCESS RETRIEVE "$key"
@@ -288,7 +309,7 @@ while read -r line; do
 				query="name = '$key' and '$FID' in parents and trashed = false"
 			fi
 
-			if ! check_result=$(gdrive list -q "$query" --no-header --bytes --name-width 0 2>&1)
+			if ! check_result=$(gdrive list $CONFIG -q "$query" --no-header --bytes --name-width 0 2>&1)
 			then
 				echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-gdrive failed to parse gdrive output"
 			else
@@ -306,12 +327,12 @@ while read -r line; do
 			query="name = '$key' and '$FID' in parents and trashed = false"
 			# Note that it's not a failure to remove a
 			# key that is not present.
-			if [[ ! $(gdrive list -q "$query" --no-header 2>&1) ]]
+			if [[ ! $(gdrive list $CONFIG -q "$query" --no-header 2>&1) ]]
 			then
 				echo REMOVE-SUCCESS "$key"
 			else
-				FID=$(gdrive list -q "$query" -m 1 --no-header | awk '{print $1}')
-				if runcmd gdrive delete "$FID"; then
+				FID=$(gdrive list $CONFIG -q "$query" -m 1 --no-header | awk '{print $1}')
+				if runcmd gdrive delete $CONFIG "$FID"; then
 		                	echo REMOVE-SUCCESS "$key"
 	                	else
                 		        echo REMOVE-FAILURE "$key"
