Update checkpresent

diff --git a/git-annex-remote-gdrive b/git-annex-remote-gdrive
--- a/git-annex-remote-gdrive
+++ b/git-annex-remote-gdrive
@@ -214,25 +214,18 @@ while read -r line; do
 		CHECKPRESENT)
 			key="$2"
 			calclocation "$key"
-
-			if check_result=$(gdrive size "$LOC$key" 2>&1) &&
-			    echo $check_result|grep 'Total objects: 1 Total size' >&2 &&
-			    ! echo $check_result|grep 'Total size: 0 (0 bytes)' >&2; then
+			if check_result=$(gdrive list -q "name = '$key' " --no-header --bytes --name-width 0 2>&1) &&
+			    echo $check_result|grep "$key" >&2; then
 				echo CHECKPRESENT-SUCCESS "$key"
 			else
-				# gdrive 1.29 used 'Total objects: 0'
-				# gdrive 1.30 uses 'directory not found'
-				if echo $check_result|grep 'Total objects: 0' >&2 || 
-				   echo $check_result|grep ' directory not found' >&2; then 
-					echo CHECKPRESENT-FAILURE "$key"
-				else
-					# When the directory does not exist,
-					# the remote is not available.
-					# (A network remote would similarly
-					# fail with CHECKPRESENT-UNKNOWN
-					# if it couldn't be contacted).
-					echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-gdrive failed to parse gdrive output"
-				fi
+				echo CHECKPRESENT-FAILURE "$key"
+				# need to implement this:
+				# When the directory does not exist,
+				# the remote is not available.
+				# (A network remote would similarly
+				# fail with CHECKPRESENT-UNKNOWN
+				# if it couldn't be contacted).
+				#echo CHECKPRESENT-UNKNOWN "$key" "remote currently unavailable or git-annex-remote-gdrive failed to parse gdrive output"
 			fi
 		;;
 		REMOVE)
